spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/apple
    username: jason
    password: 123
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      # naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQL5Dialect
  # entity-manager-factory:

server:
  port: 8080
  context-path: /AppleID
manager:
  username:
    admin
  password:
    123456